# Generated by Django 3.2.9 on 2022-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playersname', models.CharField(max_length=150)),
                ('portrait', models.ImageField(blank=True, upload_to='')),
                ('club', models.CharField(max_length=150)),
                ('bio', models.CharField(max_length=150)),
            ],
        ),
    ]
