# Generated by Django 3.2.9 on 2022-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaplayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='blizniki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='dvushki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='trelniki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='vsesrazu',
            field=models.IntegerField(default=0),
        ),
    ]
